/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    'src/templates/**/*.html',
    'src/scripts/**/*.js',
    'scripts/**/*.js',
    'config/site-config.json',
    'src/scripts/commands.json'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Brand tokens mapped to CSS variables for dynamic theming
        'brand-accent': 'var(--accent)',
        'brand-green': 'var(--green)',
        'brand-bg': 'var(--bg)',
        'brand-surface': 'var(--surface)',
        'brand-border': 'var(--border)',
        'brand-text': 'var(--text)',
        'brand-muted': 'var(--muted)',
      },
      screens: {
        'xs': '400px',
      }
    },
  },
  /* 
   * SAFELIST: Ensures dynamic classes generated by automation scripts 
   * are not purged by Tailwind's production build process.
   */
  safelist: [
    // Hero & Highlight Colors
    'text-cyan-400', 'text-teal-400', 'text-emerald-400',
    
    // Status & Certification Colors (bg-X-400/5, bg-X-400/10, border-X-400/30, text-X-400)
    { pattern: /(bg|border|text)-(blue|green|yellow|purple|orange|red|cyan|indigo|emerald|rose)-(400|500)\/(5|10|20|30)/ },
    { pattern: /(text)-(blue|green|yellow|purple|orange|red|cyan|indigo|emerald|rose)-(400|500)/ },
    
    // Core Dynamic UI
    'text-[var(--accent)]',
    'animate-pulse'
  ],
  plugins: [],
};
